# Generated by Django 5.2.5 on 2025-08-11 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_list', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prepayment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('admin_reply', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('delivered', 'Yetkazildi'), ('archived', 'Arxiv')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_quality', models.TextField(verbose_name='Xizmat sifati')),
                ('product_quality', models.TextField(verbose_name='Mahsulot sifati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
    ]
