# Generated by Django 5.2.5 on 2025-08-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_feedback_product_quality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='admin_reply',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
    ]
